FROM phusion/baseimage:0.9.16

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

RUN apt-get update && \
 apt-get upgrade -y && \
 apt-get install -y \
  firefox \
  git \
  nodejs \
  npm \
  openjdk-7-jdk \
  wget \
  xvfb

# link nodejs -> node
RUN ln -s /usr/bin/nodejs /usr/bin/node

# Mongo:
# Import MongoDB public GPG key AND create a MongoDB list file
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 7F0CEB10
RUN echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/10gen.list
RUN apt-get update && apt-get install -y mongodb-org
# Create the MongoDB data directory
RUN mkdir -p /var/lib/mongodb 

# Ruby 
RUN apt-get update && \
  apt-get install -y ruby ruby-dev ruby-bundler 

RUN mkdir /data
RUN mkdir /data/extras
ADD docker/extras/ /data/extras

### fakes3
RUN chmod +x /data/extras/fakes3-0.2.3.gem
RUN gem install builder
RUN gem install --backtrace -V --local /data/extras/fakes3-0.2.3.gem
RUN mkdir /opt/fake-s3-root
ENV CONTAINER_FAKE_S3_ENDPOINT="http://localhost:4567"

### xvfb
ADD docker/extras/xvfb.init /etc/init.d/xvfb
RUN chmod +x /etc/init.d/xvfb
RUN update-rc.d xvfb defaults

## main script
RUN mkdir -p /opt/docker/scripts
ADD docker/scripts/main.sh /opt/docker/scripts/main.sh
RUN chmod +x /opt/docker/scripts/main.sh

EXPOSE 9000

RUN mkdir -p /opt/corespring-components/regression
ADD corespring-components/regression /opt/corespring-components/regression
ENV MAIN_SCRIPT /opt/corespring-components/regression/docker/scripts/run-component-regression.sh
RUN chmod +x /opt/corespring-components/regression/docker/scripts/run-component-regression.sh

RUN mkdir /opt/utils
ADD bin /opt/utils/bin
ADD mock-data /opt/utils/mock-data

# Vars for regression testing
ENV CONTAINER_SLUG_URI "https://s3-external-1.amazonaws.com/herokuslugs/heroku.com/v1/74f625e6-13af-4126-b83a-48521b6992fa?AWSAccessKeyId=AKIAJWLOWWHPBWQOPJZQ&Signature=HEiABr2jSEu%2BIuWyHo58DoPsAJ4%3D&Expires=1459941371"
ENV TIMEOUT 60000
ENV BASE_URL http://localhost:9000
ENV GREP ""

CMD ["/opt/docker/scripts/main.sh"]

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
