#!/usr/bin/env ruby

# installation: 
# cd .git/hooks
# ln -s ../../hooks/pre-commit pre-commit

module Utils

  REGEX = /.*[M|A]\s(.*\.scala)/

  def self.get_scala_changes(log)
    lines = log.split("\n")
    matches = lines.map{ |l| REGEX.match l}
    matches.select!{ |m| !m.nil?}
    out = matches.map{ |m| m[1]}
    out
  end


  def self.clip(msg)
    if RUBY_PLATFORM.downcase.include?("darwin")
      IO.popen('pbcopy', 'w+') do |clipboard|
        clipboard.write msg
      end
      true
    elsif RUBY_PLATFORM.downcase.include?("linux")
      IO.popen('xsel --clipboard --input', 'r+') do |clipboard|
        clipboard.puts msg
      end
      true
    end
    false
  end

end

log = `git diff-index --cached HEAD`
files = Utils.get_scala_changes(log)
scalaVersion="2.10.2"

if files.length > 0
    cmd = "./hooks/bin/scalariform --test -s=#{scalaVersion} #{files.join(" ")}"
    output = `#{cmd}`

    format_cmd =  "./hooks/bin/scalariform -s=#{scalaVersion} #{files.join(" ")}"
    Utils.clip format_cmd
    if output.include? "[FAILED]"
        puts "--------------------------------------------------"
        puts "You need to format your scala code!"
        puts "run:"
        puts format_cmd
        if Utils.clip format_cmd
          puts "It has been copied to your clipboard for your convenience"
        else
          puts "It has been written to file target/clipboard.txt for your convenience"
          File.open('target/clipboard.txt', 'w') { |file| file.write(format_cmd) }
        end
        abort "--------------------------------------------------"
    end
end

=begin
if errors = `hooks/pre-commit-hooks/javascript-unicode-check`
  puts errors
  exit 1
end
=end